//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_Id { get; set; }
        public string book_Name { get; set; }
        public string author { get; set; }
        public string image { get; set; }
        public string detail { get; set; }
        public Nullable<decimal> price { get; set; }
        public string download { get; set; }
        public string type { get; set; }
    }
}
